<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/08 09:10:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_unicode_ci',
  ),
  'name' => 'doctrine',
)),);
